version: 2
updates:
  - package-ecosystem: github-actions # パッケージエコシステム
    directory: /                      # パッケージマニフェストの配置先ディレクトリ
    schedule:
      interval: "cron"
      cronjob: "*/15 * * * *"
