name: Environment variables
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main                # ジョブレベルで環境変数を定義
    steps:
      - run: echo "${BRANCH}"     # シェルコマンドからジョブレベルの環境変数を参照
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH }}  # envコンテキスト経由でジョブレベルの環境変数を参照
