name: Hello                       # ワークフロー名
on: workflow_dispatch             # イベント（手動で起動）
jobs:                             # ジョブの定義
  hello:                          # ジョブID
    runs-on: ubuntu-latest        # ランナー（Ubuntuで実行）
    steps:                        # ステップの定義
      - run: echo "Hello, GithubActions!"  # シェルコマンドの実行
      - uses: actions/checkout@v5 # アクションの呼び出し
      - uses: mxschmitt/action-tmate@v3  # tmateデバッグモード
