name: Prevent security misconfigurations
on: workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aquasecurity/trivy-action@0.33.1 # Trivyの実行
        with:
          scan-type: config                    # セキュリティ設定ミスの検出
          severity: CRITICAL,HIGH              # レポート対象の重大度
          exit-code: 1                         # 問題発見時の終了ステータス
